//////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1999 The Regents of the University of California 
// Permission to use, copy, modify, and distribute this software and
// its documentation for any purpose, without fee, and without a
// written agreement is hereby granted, provided that the above copyright 
// notice and this paragraph and the following two paragraphs appear in
// all copies. 
//
// IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
// DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
// LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
// EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
// SUCH DAMAGE. 
//
// THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
// AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
// PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS. 
//
//////////////////////////////////////////////////////////////////////////////
//
// BRASS source file
//
// SCORE runtime support
// $Revision: 1.4 $
//
//////////////////////////////////////////////////////////////////////////////

#include "ScoreConfig.h"

unsigned int numPhysicalPages = SCORE_DEFAULT_NUMPHYSICALPAGES;
unsigned int numPhysicalSegments = SCORE_DEFAULT_NUMPHYSICALSEGMENTS;
unsigned int physicalSegmentSize = SCORE_DEFAULT_PHYSICALSEGMENTSIZE;
unsigned int SCORE_TIMESLICE = SCORE_DEFAULT_TIMESLICE;
unsigned int SCORE_FAKE_SCHEDULER_TIME = SCORE_DEFAULT_FAKE_SCHEDULER_TIME;
unsigned int SCORE_STALL_THRESHOLD = SCORE_DEFAULT_STALL_THRESHOLD;
float SCORE_CLUSTERFREEABLE_RATIO = SCORE_DEFAULT_CLUSTERFREEABLE_RATIO;
unsigned int SCORE_DATASEGMENTBLOCK_LOADSIZE = SCORE_DEFAULT_DATASEGMENTBLOCK_LOADSIZE;
unsigned int SCORE_PAGECONFIG_SIZE = SCORE_DEFAULT_PAGECONFIG_SIZE;
unsigned int SCORE_PAGESTATE_SIZE = SCORE_DEFAULT_PAGESTATE_SIZE;
unsigned int SCORE_PAGEFIFO_SIZE = SCORE_DEFAULT_PAGEFIFO_SIZE;
unsigned int SCORE_MEMSEGFIFO_SIZE = SCORE_DEFAULT_MEMSEGFIFO_SIZE;
unsigned int SCORE_NUM_CONSECUTIVE_DEADLOCKS_TO_KILL = SCORE_DEFAULT_NUM_CONSECUTIVE_DEADLOCKS_TO_KILL;
unsigned int SCORE_SEGMENTTABLE_LEVEL0SIZE = SCORE_DEFAULT_SEGMENTTABLE_LEVEL0SIZE;
unsigned int SCORE_SEGMENTTABLE_LEVEL1SIZE = SCORE_DEFAULT_SEGMENTTABLE_LEVEL1SIZE;

unsigned int SIM_COST_GETARRAYSTATUS = SIM_DEFAULT_COST_GETARRAYSTATUS;
unsigned int SIM_COST_STARTPAGE = SIM_DEFAULT_COST_STARTPAGE;
unsigned int SIM_COST_STOPPAGE = SIM_DEFAULT_COST_STOPPAGE;
unsigned int SIM_COST_STARTSEGMENT = SIM_DEFAULT_COST_STARTSEGMENT;
unsigned int SIM_COST_STOPSEGMENT = SIM_DEFAULT_COST_STOPSEGMENT;
unsigned int SIM_COST_DUMPPAGESTATE = SIM_DEFAULT_COST_DUMPPAGESTATE;
unsigned int SIM_COST_DUMPPAGEFIFO = SIM_DEFAULT_COST_DUMPPAGEFIFO;
unsigned int SIM_COST_LOADPAGECONFIG = SIM_DEFAULT_COST_LOADPAGECONFIG;
unsigned int SIM_COST_LOADPAGESTATE = SIM_DEFAULT_COST_LOADPAGESTATE;
unsigned int SIM_COST_LOADPAGEFIFO = SIM_DEFAULT_COST_LOADPAGEFIFO;
unsigned int SIM_COST_GETSEGMENTPOINTERS = SIM_DEFAULT_COST_GETSEGMENTPOINTERS;
unsigned int SIM_COST_DUMPSEGMENTFIFO = SIM_DEFAULT_COST_DUMPSEGMENTFIFO;
unsigned int SIM_COST_SETSEGMENTCONFIGPOINTERS = 
  SIM_DEFAULT_COST_SETSEGMENTCONFIGPOINTERS;
unsigned int SIM_COST_CHANGESEGMENTMODE = SIM_DEFAULT_COST_CHANGESEGMENTMODE;
unsigned int SIM_COST_CHANGESEGMENTTRAANDPBOANDMAX = 
  SIM_DEFAULT_COST_CHANGESEGMENTTRAANDPBOANDMAX;
unsigned int SIM_COST_RESETSEGMENTDONEFLAG = 
  SIM_DEFAULT_COST_RESETSEGMENTDONEFLAG;
unsigned int SIM_COST_LOADSEGMENTFIFO = SIM_DEFAULT_COST_LOADSEGMENTFIFO;
float SIM_COST_MEMXFERPRIMARYTOCMB = SIM_DEFAULT_COST_MEMXFERPRIMARYTOCMB;
float SIM_COST_MEMXFERCMBTOPRIMARY = SIM_DEFAULT_COST_MEMXFERCMBTOPRIMARY;
float SIM_COST_MEMXFERCMBTOCMB = SIM_DEFAULT_COST_MEMXFERCMBTOCMB;
unsigned int SIM_COST_CONNECTSTREAM = SIM_DEFAULT_COST_CONNECTSTREAM;

#if ASPLOS2000
unsigned int SCORE_NUM_PAGENODES_IN_CP = SCORE_DEFAULT_NUM_PAGENODES_IN_CP;
#endif
