#ifndef _ScoreType_H
#define _ScoreType_H

enum ScoreType {SCORE_STREAM_UNTYPED,
		SCORE_STREAM_SIGNED_TYPE,
		SCORE_STREAM_UNSIGNED_TYPE,
		SCORE_STREAM_BOOLEAN_TYPE,
		SCORE_STREAM_FLOAT_TYPE,
		SCORE_STREAM_DOUBLE_TYPE};
#endif
