a.out:	add.C ../libScoreRuntime.a add8.cc add8.h
	g++ -I/opt/leda/incl -I/home/nachiket/workspace/ScoreRuntime -L/home/nachiket/workspace/ScoreRuntime -L/opt/leda add.C add8.cc -lleda -lX11 -lScoreRuntime -lpthread
clean:
	rm a.out
